/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Fluid Architect Design System — M3 Tonal Palette
                'on-surface': '#dee5ff',
                'on-secondary': '#005c52',
                'inverse-primary': '#4954bc',
                'surface': '#060e20',
                'on-secondary-container': '#dcfff7',
                'primary': '#9fa7ff',
                'secondary-container': '#006b5f',
                'inverse-surface': '#faf8ff',
                'secondary-fixed-dim': '#50ebd5',
                'error-dim': '#d73357',
                'surface-container-high': '#141f38',
                'on-primary-fixed': '#000000',
                'error-container': '#a70138',
                'background': '#060e20',
                'surface-container-lowest': '#000000',
                'on-error': '#490013',
                'surface-variant': '#192540',
                'tertiary-dim': '#9c48ea',
                'primary-dim': '#8a95ff',
                'inverse-on-surface': '#4d556b',
                'tertiary-fixed': '#ce9bff',
                'primary-fixed-dim': '#7f8af6',
                'on-background': '#dee5ff',
                'on-error-container': '#ffb2b9',
                'surface-dim': '#060e20',
                'primary-container': '#8d98ff',
                'outline-variant': '#40485d',
                'tertiary-fixed-dim': '#c488ff',
                'secondary': '#62fae3',
                'on-tertiary': '#33005b',
                'on-secondary-fixed-variant': '#00675c',
                'on-tertiary-fixed': '#270048',
                'surface-container-highest': '#192540',
                'on-tertiary-fixed-variant': '#560094',
                'on-tertiary-container': '#000000',
                'tertiary': '#c180ff',
                'error': '#ff6e84',
                'primary-fixed': '#8d98ff',
                'surface-container': '#0f1930',
                'secondary-fixed': '#62fae3',
                'outline': '#6d758c',
                'on-primary-container': '#000a7b',
                'surface-container-low': '#091328',
                'on-secondary-fixed': '#004840',
                'tertiary-container': '#af5cfe',
                'on-surface-variant': '#a3aac4',
                'on-primary-fixed-variant': '#0c1889',
                'on-primary': '#101b8b',
                'secondary-dim': '#50ebd5',
                'surface-tint': '#9fa7ff',
                'surface-bright': '#1f2b49',
            },
            borderRadius: {
                DEFAULT: '1rem',
                'lg': '2rem',
                'xl': '3rem',
                'full': '9999px',
            },
            fontFamily: {
                headline: ['Manrope', 'sans-serif'],
                body: ['Manrope', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
            animation: {
                'fade-in': 'fadeIn 0.3s ease-in',
                'slide-in': 'slideIn 0.4s ease-out',
                'slide-in-right': 'slideInRight 0.3s ease-out',
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                'float': 'float 6s ease-in-out infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideIn: {
                    '0%': { transform: 'translateY(10px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideInRight: {
                    '0%': { transform: 'translateX(100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 5px rgba(159, 167, 255, 0.3)' },
                    '100%': { boxShadow: '0 0 20px rgba(159, 167, 255, 0.6)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
            },
        },
    },
    plugins: [],
}
